---
title: "Untitled"
output: html_document
---

```{r}
library(ISLR)
library(glmnet)
library(plotmo)
```

```{r}
data("Credit")

Credit

```

```{r}
fit <- leaps::regsubsets(Balance ~.,
                  data = Credit,
                  method = "exhaustive",
                  nvmax = 11)
summ <- summary(fit)
summ$adjr2
```

```{r}
predict.regsubsets <- function(object, newdata, id, ...) {
  form <- as.formula(object$call[[2]])
  matrix1 <- model.matrix(form, newdata)
  coefs <- coef(object, id = id)
  
  return(matrix1[ , names(coefs)] %*% coefs)
}
```

```{r}
new_data <- Credit %>% head(10)
fit %>% predict(newdata = new_data,id = 5)
```

```{r}
Credit1 <- Credit[,-1]
```

```{r}
X <- model.matrix(Balance ~ .,data = Credit1)[,-1]
y <- Credit1$Balance
```

```{r}
tr <- sample(nrow(x),.8*nrow(x))
```

```{r}
X <- scale(X,center = TRUE,scale = TRUE)
```

```{r}
ridge <- glmnet(X[tr,],y[tr],
                alpha = 0,
                standardize = FALSE)
```

```{r}
plot_glmnet(ridge)
```

```{r}
parsnip::linear_reg(mode = "regression",penalty = 1,mixture = 0) %>% 
  set_engine("glmet")
```

