---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
set.seed(123)
library(tidyverse)


x <- rep(1:30,each = 10)
beta <- rep(c(2,55,24),each = 100)
y <- beta + rnorm(length(x),0,3)

plot(x,y,col = "blue")
```

```{r}
cut_points <- (unique(x) %>% head(-1) + unique(x) %>% tail(-1))/2
```

```{r}
mean((y-mean(y))^2)
```

```{r}
results <- tibble(cut_point = cut_points,mse = NA)
```

```{r}
i <- 0
for (cut in cut_points) {
   i = i + 1
   
   rss1_val <- y[x<cut]
   rss2_val <- y[x>cut]
   
   rss1_mean <-rss1_val %>% mean()
   rss2_mean <-rss2_val %>% mean()
   
   rss1_error <- rss1_val - rss1_mean
   rss2_error <- rss2_val - rss2_mean
   
   rss1_mse <- rss1_error ^ 2 %>% mean()
   rss2_mse <- rss2_error ^ 2 %>% mean()
   
   results[i,2] <- rss1_mse + rss2_mse
}
```

```{r}
plot(results,type = "b")
```
```{r}
i <- 0
results <- tibble(cut_point = cut_points[cut_points  > 10.5],mse = NA)
for (cut in cut_points[cut_points  > 10.5]) {
  
   i = i + 1
   
   rss1_val <- y[x<cut & x> 10.5]
   rss2_val <- y[x>cut & x> 10.5]
   
   rss1_mean <-rss1_val %>% mean()
   rss2_mean <-rss2_val %>% mean()
   
   rss1_error <- rss1_val - rss1_mean
   rss2_error <- rss2_val - rss2_mean
   
   rss1_mse <- rss1_error ^ 2 %>% mean()
   rss2_mse <- rss2_error ^ 2 %>% mean()
   
   results[i,2] <- rss1_mse + rss2_mse
}
```


```{r}
results %>% plot(type = "b")
```

```{r}
tree <- rpart::rpart(y~x)

plot_tree <- tree %>% partykit::as.party() %>% plot()
```

```{r}
library(tidymodels)
```


```{r}
model <- parsnip::decision_tree(mode = "regression")
fit_model <- model %>% 
  set_engine("rpart") %>% 
  fit(x~y,data = tibble(x,y))
```

```{r}
fit_model$fit %>% rpart.plot::rpart.plot(roundint = FALSE)
```


```{r}
library(ISLR)
```

```{r}
model <- parsnip::decision_tree(mode = "regression")
fit_model <- model %>% 
  set_engine("rpart") %>% 
  fit(Balance~.,data = Credit)

```

```{r}
fit_model[["fit"]] %>% rpart.plot::rpart.plot(roundint = FALSE)
```

```{r}
Cp %>% range_set(range = c(-10,-1))

Cp %>% value_seq(n = 20)
```
```{r}
fit_model %>% pluck("fit") %>% rpart::plotcp()
```


```{r}
model %>% 
  set_args(cost_complexity = 0) %>% 
  set_engine("rpart") %>% 
  fit(Balance ~.,data = Credit) %>% 
  pluck("fit") %>% 
  rpart::plotcp()
```


# Wine Data

```{r}
library(readr)
 library(readr)
wine <- read_delim("data/winequality-red.csv",
                              ";", 
                              escape_double = FALSE,
                              trim_ws = TRUE)
```


```{r}
wine
```


```{r}
wine <- wine %>% 
  mutate(quality = if_else(quality > 6,"good","bad") %>% as_factor())
wine_split <- initial_split(wine, prop = 0.8)


wine_recipe <- training(wine_split) %>%
recipe(quality~.) %>%
  #step_center(all_numeric(), -all_outcomes()) %>%
  #step_scale(all_numeric(), -all_outcomes()) %>%
  prep()

wine_testing <- wine_recipe %>%
  bake(testing(wine_split)) 

wine_training <- wine_recipe %>% juice()

glimpse(wine_training)
glimpse(wine_testing)
```

```{r}
logistic_regression <- logistic_reg(mode = "classification") %>% 
  set_engine("glm") %>% 
  fit(quality ~ .,data = wine_training)

testing_metrics <- function(model_fit_wine,testing_df) {
  
  wine_class <- model_fit_wine %>% 
  predict(wine_testing,type = "class") 

wine_probs <- model_fit_wine %>% 
  predict(wine_testing,type = "prob")

wine_df <- bind_cols(wine_class,wine_probs,testing_df %>% select(quality))
  
}

```

```{r}

classification_model <- logistic_reg(mode = "classification") %>% 
  set_engine("glm") %>% 
  fit(quality ~ .,data = wine_training)

model_results <- classification_model %>% 
  testing_metrics(testing_df = wine_testing) 

model_results

matrix_results <- model_results %>% 
  conf_mat(quality,.pred_class)

matrix_results

metrics_results <- model_results %>% 
  metrics(quality,.pred_class,.pred_bad)

metrics_results

roc_results <- model_results %>% 
  roc_curve(truth = quality,.pred_bad)

roc_results

roc_curve_plot <- roc_results %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_path() +
  geom_abline(lty = 3) +
  coord_equal() +
  theme_bw()

roc_curve_plot
```

```{r}

classification_model <- parsnip::decision_tree(mode = "classification") %>% 
  set_engine("rpart") %>% 
  fit(quality ~ .,data = wine_training)

model_results <- classification_model %>% 
  testing_metrics(testing_df = wine_testing) 

model_results

matrix_results <- model_results %>% 
  conf_mat(quality,.pred_class)

matrix_results

metrics_results <- model_results %>% 
  metrics(quality,.pred_class,.pred_bad)

metrics_results

roc_results <- model_results %>% 
  roc_curve(truth = quality,.pred_bad)

roc_results

roc_curve_plot <- roc_results %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_path() +
  geom_abline(lty = 3) +
  coord_equal() +
  theme_bw()

roc_curve_plot

classification_model %>% pluck("fit") %>% rpart::plotcp()
```


```{r}

classification_model <- decision_tree(mode = "classification",cost_complexity = 0.057) %>% 
  set_engine("rpart") %>% 
  fit(quality ~ .,data = wine_training)

model_results <- classification_model %>% 
  testing_metrics(testing_df = wine_testing) 

model_results

matrix_results <- model_results %>% 
  conf_mat(quality,.pred_class)

matrix_results

metrics_results <- model_results %>% 
  metrics(quality,.pred_class,.pred_bad)

metrics_results

roc_results <- model_results %>% 
  roc_curve(truth = quality,.pred_bad)

roc_results

roc_curve_plot <- roc_results %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_path() +
  geom_abline(lty = 3) +
  coord_equal() +
  theme_bw()

roc_curve_plot
```

```{r}

classification_model <- parsnip::nearest_neighbor(mode = "classification") %>% 
  set_engine("kknn") %>% 
  fit(quality ~ .,data = wine_training)

model_results <- classification_model %>% 
  testing_metrics(testing_df = wine_testing) 

model_results

matrix_results <- model_results %>% 
  conf_mat(quality,.pred_class)

matrix_results

metrics_results <- model_results %>% 
  metrics(quality,.pred_class,.pred_bad)

metrics_results

roc_results <- model_results %>% 
  roc_curve(truth = quality,.pred_bad)

roc_results

roc_curve_plot <- roc_results %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_path() +
  geom_abline(lty = 3) +
  coord_equal() +
  theme_bw()

roc_curve_plot
```

